trigger:
- master

jobs:
- job: 'Build'
  strategy:
    matrix:
      windows:
        imageName: 'windows-latest'
        plat: 'win'
        rid: 'win'
        def: '-DBUILD_WINDOWS=on'
      windows_gtk:
        imageName: 'windows-latest'
        plat: 'win'
        rid: 'win-gtk'
        def: '-DBUILD_GTK3=on'
      linux:
        imageName: 'ubuntu-latest'
        plat: 'linux'
        rid: 'linux'
        def: '-DBUILD_GTK3=on'
      mac:
        imageName: 'macos-latest'
        plat: 'mac'
        rid: 'mac'
        def: '-DBUILD_COCOA=on'
      mac_gtk:
        imageName: 'macos-latest'
        plat: 'mac'
        rid: 'mac-gtk'
        def: '-DBUILD_GTK3=on'
  pool:
    vmImage: $(imageName)

  steps:
  - script: |
      vcpkg install libxml2:x64-windows wil:x64-windows
    displayName: 'Install libxml2 & wil'
    condition: eq(variables.rid, 'win')

  - script: |
      vcpkg install libxml2:x64-windows gtk:x64-windows
    displayName: 'Install libxml2 & gtk'
    condition: eq(variables.rid, 'win-gtk')

  - script: |
      sudo apt install software-properties-common
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt-get install gcc-9 g++-9 libgtk-3-dev ninja-build
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-
    displayName: 'Install linux dependencies'
    condition: eq(variables.rid, 'linux')

  - script: |
      brew install ninja
    displayName: 'Install ninja'
    condition: eq(variables.plat, 'mac')

  - script: |
      brew install gtk+3 pkgconfig
    displayName: 'Install gtk'
    condition: eq(variables.rid, 'mac-gtk')

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      mkdir build & cd build
      cmake .. -GNinja $(def) -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/$(rid) -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=$(VCPKG_INSTALLATION_ROOT)/scripts/buildsystems/vcpkg.cmake
    displayName: 'Configure all projects'
    condition: eq(variables.plat, 'win')

  - task: CMake@1
    displayName: 'Configure all projects'
    condition: ne(variables.plat, 'win')
    inputs:
      cmakeArgs: .. $(def) -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/$(rid)

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      cd build
      ninja install
    displayName: 'Install all projects'
    condition: eq(variables.plat, 'win')

  - task: CMake@1
    displayName: 'Install all projects'
    condition: ne(variables.plat, 'win')
    inputs:
      cmakeArgs: --build . --target install --config Release

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      mkdir build\debug & cd build\debug
      cmake ..\.. -GNinja $(def) -DCMAKE_CXX_COMPILER=cl -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory)/$(rid)/debug -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=$(VCPKG_INSTALLATION_ROOT)/scripts/buildsystems/vcpkg.cmake
    displayName: 'Configure all projects for Debug'
    condition: eq(variables.plat, 'win')

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
      cd build\debug
      ninja install
    displayName: 'Install all projects for Debug'
    condition: eq(variables.plat, 'win')

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'
    inputs:
      artifactName: 'publish'

- job: 'Build_winrt'
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: 'XamlCpp.WinRT.sln'

  steps:
  - task: NuGetCommand@2
    displayName: 'Restore solution'
    inputs:
      restoreSolution: '$(solution)'

  - task: MSBuild@1
    displayName: 'Build solution'
    inputs:
      solution: '$(solution)'
      configuration: 'Release'
